//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.ActionDetials = new HashSet<ActionDetial>();
            this.ArticalToBookDetails = new HashSet<ArticalToBookDetail>();
            this.AuthorDetails = new HashSet<AuthorDetail>();
            this.CategoryDetails = new HashSet<CategoryDetail>();
            this.Comments = new HashSet<Comment>();
            this.Discount_Detail = new HashSet<Discount_Detail>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.PainterDetails = new HashSet<PainterDetail>();
            this.Previews = new HashSet<Preview>();
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
            this.TranslatorDetails = new HashSet<TranslatorDetail>();
        }
    
        public int BookID { get; set; }
        public string BookTitle { get; set; }
        public string AboutAuthor { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public System.DateTime PublicationDate { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public decimal UnitPrice { get; set; }
        public string Introduction { get; set; }
        public string ISBN { get; set; }
        public string BindingMethod { get; set; }
        public string Pages { get; set; }
        public string Dimensions { get; set; }
        public Nullable<int> UnitInStock { get; set; }
        public string CoverPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionDetial> ActionDetials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticalToBookDetail> ArticalToBookDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorDetail> AuthorDetails { get; set; }
        public virtual Language Language { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryDetail> CategoryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discount_Detail> Discount_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PainterDetail> PainterDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preview> Previews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranslatorDetail> TranslatorDetails { get; set; }
    }
}
