//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerService
    {
        public int CRMID { get; set; }
        public int StatusID { get; set; }
        public string CContent { get; set; }
        public string ReplyContent { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> Satisfaction { get; set; }
        public int MemberID { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Status Status { get; set; }
    }
}
